{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-predictor
  labels:
    app: {{ .Release.Name }}-predictor
spec:
  path: /
  to:
    kind: Service
    name: {{ .Release.Name }}-predictor
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
