image: docker.io/postgrest/postgrest:latest
replicas: 1
port: 3000

postgresql:
  host: postgresql
  port: 5432
  user: app_user
  password: password
  database: appdb

route:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
