image: langflowai/langflow:latest
replicas: 1
storage: 1Gi
port: 7860

autoLogin: "true"

route:
  enabled: true

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi
