endpoint: https://llama-stack-user1-canopy.apps.ocp.9xgvv.sandbox3434.opentlc.com
user_id: hbadawy
model: vllm/llama32
embedding_model: granite-embedding-125m
embedding_dimension: 768
vector_io_provider: milvus
safety_enabled: true
input_shields:
- hap
- prompt_injection
- language_detection
- regex
output_shields:
- hap
- language_detection
language: English
system_prompt: you are a helpful assistant
temperature: 0.1
top_p: 0.9
max_tokens: 1024
