image: docker.io/dpage/pgadmin4:latest
replicas: 1
port: 5050

email: "admin@example.com"
password: "admin"

route:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
