apiVersion: v1
kind: ConfigMap
metadata:
  name: fms-orchestr8-config-gateway
  labels:
    app: fmstack-nlp
    app.kubernetes.io/name: guardrails-orchestrator
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    orchestrator:
      host: "localhost"
      port: {{ .Values.server.port }}
    detectors:
    {{- range $name, $detector := .Values.detectors }}
    {{- if $detector.enabled }}
      - name: {{ $name }}
        input: {{ hasKey $detector "input" | ternary $detector.input true }}
        output: {{ hasKey $detector "output" | ternary $detector.output true }}
        detector_params: {{ $detector.params | toJson }}
    {{- end }}
    {{- end }}
    routes:
      - name: all
        detectors:
        {{- range $name, $detector := .Values.detectors }}
        {{- if $detector.enabled }}
          - {{ $name }}
        {{- end }}
        {{- end }}
    {{- range $routeName, $routeConfig := .Values.customRoutes }}
      - name: {{ $routeName }}
        detectors:
        {{- range $routeConfig.detectors }}
          - {{ . }}
        {{- end }}
        {{- if $routeConfig.fallback_message }}
        fallback_message: {{ $routeConfig.fallback_message | quote }}
        {{- end }}
    {{- end }}
      - name: passthrough
        detectors:
