apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardrails-orchestrator-sa
  labels:
    app: guardrails-orchestrator
    app.kubernetes.io/name: guardrails-orchestrator
    app.kubernetes.io/instance: {{ .Release.Name }}
