apiVersion: v2
name: dashy
description: Dashy dashboard with workspace view for managing AI platform services on OpenShift
type: application
version: 0.2.0
appVersion: "latest"
icon: https://raw.githubusercontent.com/Lissy93/dashy/master/public/web-icons/dashy-logo.png
keywords:
  - dashy
  - dashboard
  - ui
  - openshift
maintainers:
  - name: hasanbadawy
