endpoint: ""
user_id: ""
model: ""
embedding_model: ""
embedding_dimension: 768
vector_io_provider: milvus
safety_enabled: false
input_shields: []
output_shields: []
language: English
system_prompt: You are a helpful assistant
temperature: 0.1
top_p: 0.9
max_tokens: 2000
